import { NextPage } from "next";
import Head from "next/head";
import { CoffeeDescription } from "../../../components/CoffeeDescription";
import { Footer } from "../../../components/Footer";
import { Header } from "../../../components/Header";
import { ProductInfo } from "../../../components/ProductInfo";

const Product: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <ProductInfo />
        <CoffeeDescription />
        <Footer />
      </main>
    </>
  );
};

export default Product;
