import type { NextPage } from "next";
import Head from "next/head";

import { ColorGuide } from "../components/ColorGuide";
import { Footer } from "../components/Footer";
import { Header } from "../components/Header";
import { Hero } from "../components/Hero";
import { InstaLayout } from "../components/InstaLayout";
import { NewArrivals } from "../components/NewArrivals";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="overflow-hidden">
          <Hero />
        </div>

        <div className="mx-5 my-7 bg-white">
          <NewArrivals />
        </div>
        <div className="mx-5 mb-7">
          <ColorGuide />
        </div>
        <div className="mx-5 mb-7">
          <InstaLayout />
        </div>
        <div>
          <Footer />
        </div>
      </main>
    </>
  );
};

export default Home;
